#!/usr/bin/env -S uv run
# /// script
# dependencies = []
# ///
"""make_adw — generate a new one-shot ADW script from agents in the config.

Usage:
    uv run <skill>/scripts/make_adw.py --name review-docs --agents scout,builder

Each named agent becomes one agent phase, chained by envelope. Starter agents
map to their concrete output types; unknown agents get GenericOutput (define a
concrete type in adw_modules/data_types.py and swap it in). A builder enters the shared delivery pipeline for checks, independent review,
bounded repair, documentation, commits and target-aware acceptance.
"""

import argparse
import re
import sys
from pathlib import Path

OUTPUT_TYPES = {"planner": "PlanOutput", "decomposer": "DecomposeOutput", "builder": "BuildOutput",
                "scout": "ScoutOutput",
                "reviewer": "ReviewOutput", "documenter": "DocumentDraftOutput"}

HEADER = '''#!/usr/bin/env -S uv run
# /// script
# dependencies = ["openai-codex==0.155.1", "pydantic", "python-dotenv", "pyyaml", "rich"]
# ///
"""ADW {title} — generated by make_adw.

Usage:
    uv run adws/adw-{name}.py "<prompt or path/to/prompt.md>" [--config adws/adw_sssf_config/sssf.config.yaml] [--adw-id a1b2c3d4]

Phases: engineer(request) -> {chain}
"""

import argparse
import sys

from adw_modules import delivery, agents, changes, gates, git_helper, review_routing, session, spec_artifacts, tickets, utils
from adw_modules.data_types import BuildInput, AgentCall, ChangeCapture, DocumentRequest, PhaseParams, PlanningTarget, TicketSelection, WorkflowOptions, {imports}

REQUIRED_AGENTS = {agents_list}


def main(prompt: str, options: WorkflowOptions | None = None) -> int:
    options = options or WorkflowOptions()
{target_preflight}
    cfg = agents.load_config(options.config)
    agents.validate(cfg, REQUIRED_AGENTS)
    run = session.ensure(cfg, options.adw_id)
{build_base}

    with run.phase(PhaseParams(name="request", kind="engineer", owner=run.engineer,
                               description="Capture the incoming ask")) as ph:
        ph.log(input=prompt)

    previous = None
    source_spec = options.spec or prompt
    work_item = tickets.spec_work_item(run.repo_root, options.spec) if options.spec else None
    selection = options.selection
    last_review = None
    last_receipt = None
    accepted = True
{phases}
    return run.finish(accepted=accepted, reason="a generated review did not approve the selected target")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prompt", help="inline text or a path to a prompt file")
    parser.add_argument("--config", default="adws/adw_sssf_config/sssf.config.yaml")
    parser.add_argument("--adw-id", default=None, help="join or pin an existing session")
    parser.add_argument("--ticket-id", help="explicit ticket selected after decomposition")
    parser.add_argument("--dependency-evidence")
    goal = parser.add_mutually_exclusive_group(required={target_required})
    goal.add_argument("--spec-dir")
    goal.add_argument("--spec")
    args = parser.parse_args()
    selection = TicketSelection(ticket_id=args.ticket_id, dependency_evidence=args.dependency_evidence) if args.ticket_id else None
    target = PlanningTarget(spec_dir=args.spec_dir, spec=args.spec) if {has_planner} else None
    if not {has_planner} and args.spec_dir:
        parser.error("--spec-dir requires a planner phase")
    options = WorkflowOptions(config=args.config, adw_id=args.adw_id, planning_target=target,
                              spec=None if {has_planner} else args.spec, selection=selection)
    sys.exit(main({prompt_expression}, options))
'''

PHASE = '''    # TODO: replace this description — say what THIS phase does and why.
    with run.phase(PhaseParams(name="{name}", kind="agent", owner="{agent}",
                               retries=1, description="Run {agent} over the request and hand its envelope on")) as ph:
        previous = ph.call(AgentCall(output_type={output_type}, prompt=prompt,
                                     previous=previous, work_item=work_item{planning},
                                     gates=[gates.artifacts_exist{review_gate}]))
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="lowercase hyphen-separated workflow name")
    parser.add_argument("--agents", required=True, help="comma-separated agent names, in order")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    args.name = args.name.replace("_", "-")
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:-[a-z0-9]+)*", args.name):
        parser.error("name must contain lowercase words separated by hyphens")
    agent_names = [a.strip() for a in args.agents.split(",") if a.strip()]
    if not agent_names:
        print("no agents given")
        return 1

    if agent_names == ["documenter"]:
        parser.error("documenter is a stage of a business workflow, not a standalone workflow")
    if "builder" in agent_names:
        tail = agent_names[agent_names.index("builder") + 1:]
        if tail not in ([], ["reviewer"], ["reviewer", "documenter"]):
            parser.error("builder enters the complete delivery chain; only reviewer/documenter may follow")
    types = [OUTPUT_TYPES.get(a, "GenericOutput") for a in agent_names]
    seen: dict[str, int] = {}
    phases = []
    for position, (agent, output_type) in enumerate(zip(agent_names, types)):
        seen[agent] = seen.get(agent, 0) + 1
        phase_name = agent if seen[agent] == 1 else f"{agent}_{seen[agent]}"
        if agent == "builder":
            phases.append('    work_item = work_item or delivery.resolve_input(run, BuildInput(prompt=prompt))\n'
                          '    return delivery.execute(run, delivery.DeliveryRequest(prompt, work_item, build_base, previous))\n')
            break
        if agent == "decomposer":
            phases.append('    previous = tickets.decompose(run, source_spec)\n')
            if "builder" in agent_names[position + 1:]:
                phases.append('    with run.phase(PhaseParams(name="select_ticket", kind="code", owner="tickets", description="Validate explicit ticket selection and prerequisite evidence")) as ph:\n'
                              '        work_item = tickets.select_ticket(run, previous, selection)\n'
                              '        ph.log(work_item=work_item.model_dump())\n')
            elif "documenter" in agent_names[position + 1:]:
                phases.append('    work_item = tickets.spec_work_item(run.repo_root, source_spec)\n')
        elif agent == "documenter":
            phases.append(f'''    if work_item is None:
        raise ValueError("documenter requires an explicit root spec or selected ticket")
    document_changes = changes.as_envelope(changes.capture(run, ChangeCapture(base=build_base)), "Actual execution changes")
    previous = spec_artifacts.document(run, DocumentRequest(work_item=work_item,
        purpose=prompt, changes=document_changes, review=last_review,
        review_receipt=tickets.artifact(run.repo_root, spec_artifacts.relative(run, last_receipt), ".json") if last_receipt else None), name="{phase_name}")
    spec_artifacts.prepare_finish(run, previous)
''')
        else:
            phases.append(PHASE.format(name=phase_name, agent=agent, output_type=output_type,
                                       planning=", planning_target=options.planning_target" if agent == "planner" else "",
                                       review_gate=", gates.verdict_consistent" if agent == "reviewer" else ""))
        if agent == "reviewer":
            blocked_document = ""
            if "documenter" in agent_names[position + 1:]:
                blocked_document = """    if decision.action != "approve":
        if work_item is None:
            raise ValueError("blocked documentation requires an explicit spec")
        document = spec_artifacts.document(run, DocumentRequest(work_item=work_item,
            purpose=decision.reason, review=previous,
            changes=changes.as_envelope(changes.capture(run, ChangeCapture(base=build_base)), decision.reason),
            review_receipt=tickets.artifact(run.repo_root, spec_artifacts.relative(run, receipt), ".json")))
        spec_artifacts.prepare_finish(run, document)"""
            phases.append(f'''    with run.phase(PhaseParams(name="route_{phase_name}", kind="code", owner="review_routing",
                               description="Persist review ownership and stop unapproved one-shot delivery")) as ph:
        decision = review_routing.decide(previous, review_routing.RoutingPolicy())
        receipt = review_routing.save(run, previous, decision,
            review_routing.ReceiptContext(prompt, build_base, work_item))
        ph.log(receipt=str(receipt), **decision.model_dump())
    last_review, last_receipt = previous, receipt
    accepted = accepted and decision.action == "approve"
{blocked_document}
    if decision.action != "approve":
        return run.finish(accepted=False, reason=decision.reason)
''')
        if agent == "planner":
            phases.append('    source_spec = previous.spec_path\n')
        if agent == "planner" and "decomposer" not in agent_names:
            phases.append('    work_item = tickets.spec_work_item(run.repo_root, previous.spec_path)\n')

    chain = []
    for agent in agent_names:
        chain.append(agent)
        if agent == "builder":
            chain.extend(["code(checks)", "reviewer", "bounded repair", "documenter", "commit", "finish/acceptance"])
            break

    body = HEADER.format(
        title=args.name.replace("-", " ").title(),
        name=args.name,
        chain=" -> ".join(chain),
        imports=", ".join(sorted(set(types) | {"PlanOutput"})),
        prompt_expression=("args.prompt" if "decomposer" in agent_names and "planner" not in agent_names[:agent_names.index("decomposer")] else "utils.resolve_prompt(args.prompt)"),
        agents_list=repr(sorted(set(agent_names) | ({"reviewer", "documenter"} if "builder" in agent_names else set()))),
        build_base=(('    delivery.preflight(run)\n' if "builder" in agent_names else '') + '    build_base = git_helper.rev("HEAD")'
                    if any(a in agent_names for a in ("builder", "reviewer", "documenter")) else ""),
        phases="\n".join(phases),
        target_preflight=('    if options.planning_target is None:\n        raise ValueError("planner requires --spec-dir or --spec")' if "planner" in agent_names else
                          '    if options.spec is None:\n        raise ValueError("documenter requires --spec")' if "documenter" in agent_names and "decomposer" not in agent_names else ""),
        target_required=repr("planner" in agent_names or ("documenter" in agent_names and "decomposer" not in agent_names)),
        has_planner=repr("planner" in agent_names),
    )

    dest = Path.cwd() / "adws" / f"adw-{args.name}.py"
    if dest.exists() and not args.force:
        print(f"{dest} already exists — use --force to overwrite")
        return 1
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(body)
    print(f"wrote {dest}")
    print("next: replace each phase description — a generated one says nothing, "
          "and the description is the only intent the trace ever shows")
    print(f"run: uv run adws/adw-{args.name}.py \"your request\"")
    return 0


if __name__ == "__main__":
    sys.exit(main())
