#!/usr/bin/env -S uv run
# /// script
# dependencies = []
# ///
"""make_adw — generate a new one-shot ADW script from agents in the config.

Usage:
    uv run <skill>/scripts/make_adw.py --name review_docs --agents scout,builder

Each named agent becomes one agent phase, chained by envelope. Starter agents
map to their concrete output types; unknown agents get GenericOutput (define a
concrete type in adw_modules/data_types.py and swap it in). A builder is
followed by a deterministic Git capture, so downstream agents receive facts
from ChangesOutput rather than builder-authored paths.
"""

import argparse
import sys
from pathlib import Path

OUTPUT_TYPES = {"planner": "PlanOutput", "decomposer": "DecomposeOutput", "builder": "BuildOutput",
                "scout": "ScoutOutput",
                "reviewer": "ReviewOutput", "documenter": "DocumentOutput"}

HEADER = '''#!/usr/bin/env -S uv run
# /// script
# dependencies = ["openai-codex==0.155.1", "pydantic", "python-dotenv", "pyyaml", "rich"]
# ///
"""ADW {title} — generated by make_adw.

Usage:
    uv run adws/adw_{name}.py "<prompt or path/to/prompt.md>" [--config adws/adw_sssf_config/sssf.config.yaml] [--adw-id a1b2c3d4]

Phases: engineer(request) -> {chain}
"""

import argparse
import sys

from adw_modules import agents, changes, gates, git_helper, review_routing, session, tickets, utils
from adw_modules.data_types import AgentCall, ChangeCapture, PhaseParams, TicketSelection, {imports}

REQUIRED_AGENTS = {agents_list}


def main(prompt: str, config: str = "adws/adw_sssf_config/sssf.config.yaml", adw_id: str | None = None, selection: TicketSelection | None = None) -> int:
    cfg = agents.load_config(config)
    agents.validate(cfg, REQUIRED_AGENTS)
    run = session.ensure(cfg, adw_id)
{build_base}

    with run.phase(PhaseParams(name="request", kind="engineer", owner=run.engineer,
                               description="Capture the incoming ask")) as ph:
        ph.log(input=prompt)

    previous = None
    source_spec = prompt
    work_item = None
    accepted = True
{phases}
    return run.finish(accepted=accepted, reason="a generated review did not approve the selected target")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prompt", help="inline text or a path to a prompt file")
    parser.add_argument("--config", default="adws/adw_sssf_config/sssf.config.yaml")
    parser.add_argument("--adw-id", default=None, help="join or pin an existing session")
    parser.add_argument("--ticket-id", help="explicit ticket selected after decomposition")
    parser.add_argument("--dependency-evidence")
    args = parser.parse_args()
    selection = TicketSelection(ticket_id=args.ticket_id, dependency_evidence=args.dependency_evidence) if args.ticket_id else None
    sys.exit(main({prompt_expression}, args.config, args.adw_id, selection))
'''

PHASE = '''    # TODO: replace this description — say what THIS phase does and why.
    with run.phase(PhaseParams(name="{name}", kind="agent", owner="{agent}",
                               retries=1, description="Run {agent} over the request and hand its envelope on")) as ph:
        previous = ph.call(AgentCall(output_type={output_type}, prompt=prompt,
                                     previous=previous, work_item=work_item,
                                     gates=[gates.artifacts_exist{review_gate}]))
'''

CHANGES_PHASE = '''    with run.phase(PhaseParams(name="{name}", kind="code", owner="git",
                               description="Capture the cumulative Git diff for downstream agents")) as ph:
        changeset = changes.capture(run, ChangeCapture(base=build_base))
        ph.log(files=len(changeset.files) + len(changeset.untracked),
               lines=f"+{{changeset.insertions}} -{{changeset.deletions}}",
               diff=changeset.diff_path)
        if changeset.empty:
            raise RuntimeError("builder produced no changes")
        previous = changes.as_envelope(changeset, "Git-captured builder changes")
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", required=True, help="snake_case adw name")
    parser.add_argument("--agents", required=True, help="comma-separated agent names, in order")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    agent_names = [a.strip() for a in args.agents.split(",") if a.strip()]
    if not agent_names:
        print("no agents given")
        return 1

    types = [OUTPUT_TYPES.get(a, "GenericOutput") for a in agent_names]
    seen: dict[str, int] = {}
    phases = []
    for position, (agent, output_type) in enumerate(zip(agent_names, types)):
        seen[agent] = seen.get(agent, 0) + 1
        phase_name = agent if seen[agent] == 1 else f"{agent}_{seen[agent]}"
        if agent == "decomposer":
            phases.append('    previous = tickets.decompose(run, source_spec)\n')
            if "builder" in agent_names[position + 1:]:
                phases.append('    with run.phase(PhaseParams(name="select_ticket", kind="code", owner="tickets", description="Validate explicit ticket selection and prerequisite evidence")) as ph:\n'
                              '        work_item = tickets.select_ticket(run, previous, selection)\n'
                              '        ph.log(work_item=work_item.model_dump())\n')
        else:
            phases.append(PHASE.format(name=phase_name, agent=agent, output_type=output_type,
                                       review_gate=", gates.verdict_consistent" if agent == "reviewer" else ""))
        if agent == "reviewer":
            phases.append(f'''    with run.phase(PhaseParams(name="route_{phase_name}", kind="code", owner="review_routing",
                               description="Persist review ownership and stop unapproved one-shot delivery")) as ph:
        decision = review_routing.decide(previous, review_routing.RoutingPolicy())
        receipt = review_routing.save(run, previous, decision,
            review_routing.ReceiptContext(prompt, build_base, work_item))
        ph.log(receipt=str(receipt), **decision.model_dump())
    if decision.action != "approve":
        return run.finish(accepted=False, reason=decision.reason)
''')
        if agent == "planner":
            phases.append('    source_spec = previous.spec_path\n')
        if agent == "planner" and "decomposer" not in agent_names:
            phases.append('    work_item = tickets.spec_work_item(run.repo_root, previous.spec_path)\n')
        if agent == "builder":
            phases.append(CHANGES_PHASE.format(name=f"changes_after_{phase_name}"))

    chain = []
    for agent in agent_names:
        chain.append(agent)
        if agent == "builder":
            chain.append("code(changes)")

    body = HEADER.format(
        title=args.name.replace("_", " ").title(),
        name=args.name,
        chain=" -> ".join(chain),
        imports=", ".join(sorted(set(types) | {"PlanOutput"})),
        prompt_expression=("args.prompt" if "decomposer" in agent_names and "planner" not in agent_names[:agent_names.index("decomposer")] else "utils.resolve_prompt(args.prompt)"),
        agents_list=repr(sorted(set(agent_names))),
        build_base=('    build_base = git_helper.rev("HEAD")'
                    if "builder" in agent_names or "reviewer" in agent_names else ""),
        phases="\n".join(phases),
    )

    dest = Path.cwd() / "adws" / f"adw_{args.name}.py"
    if dest.exists() and not args.force:
        print(f"{dest} already exists — use --force to overwrite")
        return 1
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(body)
    print(f"wrote {dest}")
    print("next: replace each phase description — a generated one says nothing, "
          "and the description is the only intent the trace ever shows")
    print(f"run: uv run adws/adw_{args.name}.py \"your request\"")
    return 0


if __name__ == "__main__":
    sys.exit(main())
